name: bluecart1
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'


#------------ PACKAGES ------------#
dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  http: ^1.1.0
  logger: ^2.0.1
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.3.10
  smooth_page_indicator: ^1.1.0
  pedometer: ^4.0.1
  flutter_compass: ^0.8.0
  pedantic: ^1.11.1
  flutter_blue_plus: ^1.1.3
  flutter_svg: ^2.0.10+1
  flutter_reactive_ble: ^5.0.2
  provider: ^6.0.2
  intl: ^0.17.0

  #firebase
  firebase_core: ^2.23.0
  firebase_database: ^10.0.3
  cloud_functions: ^4.3.3


  # Icons
  cupertino_icons: ^1.0.2
  iconsax: ^0.0.8

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1


  #Product Specific



#------------ PACKAGES END ------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true


#------------ LOCAL ASSESTS ------------#
  assets:
    - assets/
    - assets/logos/
    - assets/icons/
    - assets/images/
    - assets/images/onboarding_images/
    - lib/features/authentication/screens/login/widgets/

#------------ LOCAL FONTS ------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logos/ble-light.png
