// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Oyuucu5Nnr6jdtnhgaITsb-0Xy5rsSg',
    appId: '1:785826274119:web:19e75d0ad857658e634a62',
    messagingSenderId: '785826274119',
    projectId: 'final-yr-proj-9197a',
    authDomain: 'final-yr-proj-9197a.firebaseapp.com',
    databaseURL: 'https://final-yr-proj-9197a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-yr-proj-9197a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvEDCvxJV5F7e2mcCF8KFiMDjPj4hn_5c',
    appId: '1:785826274119:android:6e9d98906716f95f634a62',
    messagingSenderId: '785826274119',
    projectId: 'final-yr-proj-9197a',
    databaseURL: 'https://final-yr-proj-9197a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-yr-proj-9197a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb8A432xUD_V4Bauwr_10vPUbPGCGyTuo',
    appId: '1:785826274119:ios:c455b7d60d73c47b634a62',
    messagingSenderId: '785826274119',
    projectId: 'final-yr-proj-9197a',
    databaseURL: 'https://final-yr-proj-9197a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-yr-proj-9197a.appspot.com',
    androidClientId: '785826274119-4rj5ol4gorjgm2fifjpv12pek0bj9fqf.apps.googleusercontent.com',
    iosClientId: '785826274119-lmnplehc5ej1an14m6hlek082s7hv720.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluecart1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6Oyuucu5Nnr6jdtnhgaITsb-0Xy5rsSg',
    appId: '1:785826274119:web:19e75d0ad857658e634a62',
    messagingSenderId: '785826274119',
    projectId: 'final-yr-proj-9197a',
    authDomain: 'final-yr-proj-9197a.firebaseapp.com',
    databaseURL: 'https://final-yr-proj-9197a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-yr-proj-9197a.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb8A432xUD_V4Bauwr_10vPUbPGCGyTuo',
    appId: '1:785826274119:ios:c455b7d60d73c47b634a62',
    messagingSenderId: '785826274119',
    projectId: 'final-yr-proj-9197a',
    databaseURL: 'https://final-yr-proj-9197a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'final-yr-proj-9197a.appspot.com',
    androidClientId: '785826274119-4rj5ol4gorjgm2fifjpv12pek0bj9fqf.apps.googleusercontent.com',
    iosClientId: '785826274119-lmnplehc5ej1an14m6hlek082s7hv720.apps.googleusercontent.com',
    iosBundleId: 'com.example.bluecart1',
  );

}